@startuml
skinparam style strictuml
skinparam dpi 180
skinparam activityMinimumWidth 220
skinparam activityPadding 18
skinparam activityShape rectangle
skinparam nodesep 80
skinparam ranksep 80
skinparam linetype ortho
skinparam defaultFontSize 13
skinparam activityFontSize 13
skinparam activityBorderThickness 1
skinparam ArrowThickness 2
skinparam SwimlaneBorderColor #000000
skinparam SwimlaneBorderThickness 2
skinparam partitionBorderColor #000000
skinparam partitionBorderThickness 2
skinparam partitionBackgroundColor #FFFFFF
skinparam BackgroundColor #FFFFFF
skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #000000
skinparam ActivityStartColor #000000
skinparam ActivityEndColor #000000
skinparam ArrowColor #000000
skinparam ActivityDiamondBackgroundColor #FFFFFF
skinparam ActivityDiamondBorderColor #000000
skinparam SwimlaneBorderColor #000000
skinparam SwimlaneTitleBackgroundColor #FFFFFF
skinparam SwimlaneTitleFontColor #000000

title Aktivitas: Mengunggah Dokumentasi Proyek


|Marketing|
start
:Membuka detail proyek;
:Memilih dokumen;
:Menambahkan keterangan dokumen;
:Klik "Upload Dokumentasi";

|Sistem|
:Memeriksa dokumen;
if (Dokumen sesuai?) then (ya)
  :Menyimpan dokumentasi proyek;
  :Menampilkan pesan berhasil;
  
  |Marketing|
  :Melihat dokumentasi baru;
  stop
else (tidak)
  :Menampilkan pesan perbaikan dokumen;
  
  |Marketing|
  :Memilih dokumen yang sesuai;
  end
endif
@enduml
