@startuml
skinparam style strictuml
skinparam dpi 180
skinparam activityMinimumWidth 220
skinparam activityPadding 18
skinparam activityShape rectangle
skinparam nodesep 80
skinparam ranksep 80
skinparam linetype ortho
skinparam defaultFontSize 13
skinparam activityFontSize 13
skinparam activityBorderThickness 1
skinparam ArrowThickness 2
skinparam SwimlaneBorderColor #000000
skinparam SwimlaneBorderThickness 2
skinparam partitionBorderColor #000000
skinparam partitionBorderThickness 2
skinparam partitionBackgroundColor #FFFFFF
skinparam BackgroundColor #FFFFFF
skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #000000
skinparam ActivityStartColor #000000
skinparam ActivityEndColor #000000
skinparam ArrowColor #000000
skinparam ActivityDiamondBackgroundColor #FFFFFF
skinparam ActivityDiamondBorderColor #000000
skinparam SwimlaneBorderColor #000000
skinparam SwimlaneTitleBackgroundColor #FFFFFF
skinparam SwimlaneTitleFontColor #000000

title Aktivitas: Membuat Penawaran Baru (Create)


|Marketing|
start
:Buka menu Penawaran;
:Klik "Tambah Penawaran";
:Pilih Klien/Customer;
:Pilih Produk / Layanan;
:Isi Judul, Deskripsi & Harga;
:Unggah File Brosur;
:Klik "Simpan Penawaran";

|Sistem|
:Validasi input data;
if (Data Valid?) then (ya)
  :Simpan file brosur;
  :Simpan data penawaran baru\n(status = 'pending');
  :Kirim notifikasi sukses;
  
  |Klien / Customer|
  :Melihat pembaruan data penawaran;
  stop
else (tidak)
  |Sistem|
  :Kirim pesan error;
  
  |Marketing|
  :Tampilkan pesan error validasi;
  end
endif
@enduml
